=== selfdenied/xml-task/data/cars.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/cars"
	xmlns:tns="http://www.example.org/cars" elementFormDefault="qualified">

	<element name="cars">
		<complexType>
			<sequence>
				<element ref="tns:abstract-car" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="abstract-vehicle">
		<sequence>
			<element name="price" type="positiveInteger" />
			<element name="speed" type="tns:top-speed" />
			<element name="weight" type="positiveInteger" />
			<element name="consumption" type="tns:fuel-consumption" />
			<element name="bodystyle" type="tns:body-style" />
			<element name="drive" type="tns:drive-arrangement" />
			<element name="gearbox" type="tns:gear-box" />
		</sequence>
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="ID">
					<pattern value="[a-zA-Z]{1}[0-9]{4}" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	<simpleType name="top-speed">
		<restriction base="positiveInteger">
			<minInclusive value="50" />
			<maxInclusive value="450" />
		</restriction>
	</simpleType>
	<simpleType name="fuel-consumption">
		<restriction base="decimal">
			<minExclusive value="0" />
		</restriction>
	</simpleType>
	<simpleType name="body-style">
		<restriction base="string">
			<enumeration value="Saloon" />
			<enumeration value="Estate" />
			<enumeration value="Hatchback" />
			<enumeration value="Coupe" />
			<enumeration value="Cabriolet" />
			<enumeration value="Offroad" />
		</restriction>
	</simpleType>
	<simpleType name="drive-arrangement">
		<restriction base="string">
			<enumeration value="FWD" />
			<enumeration value="RWD" />
			<enumeration value="AWD" />
		</restriction>
	</simpleType>
	<simpleType name="gear-box">
		<restriction base="string">
			<enumeration value="Manual" />
			<enumeration value="Automatic" />
		</restriction>
	</simpleType>

	<complexType name="combustion-vehicle">
		<complexContent>
			<extension base="tns:abstract-vehicle">
				<sequence>
					<element name="engine" type="tns:combustion-motor" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="electric-vehicle">
		<complexContent>
			<extension base="tns:abstract-vehicle">
				<sequence>
					<element name="engine" type="tns:electric-motor" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="hybrid-vehicle">
		<complexContent>
			<extension base="tns:abstract-vehicle">
				<sequence>
					<element name="engine" type="tns:combustion-motor" />
					<element name="engine" type="tns:electric-motor" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="combustion-motor">
		<sequence>
			<element name="cylinders" type="tns:cylinders-number" />
			<element name="displacement" type="positiveInteger" />
			<element name="power" type="positiveInteger" />
			<element name="torque" type="positiveInteger" />
			<element name="turbo" type="boolean" />
		</sequence>
		<attribute name="fuel" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="Petrol" />
					<enumeration value="Diesel" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	<simpleType name="cylinders-number">
		<restriction base="positiveInteger">
			<minInclusive value="2" />
			<maxInclusive value="16" />
		</restriction>
	</simpleType>

	<complexType name="electric-motor">
		<sequence>
			<element name="epower" type="positiveInteger" />
			<element name="etorque" type="positiveInteger" />
		</sequence>
		<attribute name="fuel" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="Electricity" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<element name="abstract-car" type="tns:abstract-vehicle" abstract="true" />
	<element name="combustion-car" type="tns:combustion-vehicle" substitutionGroup="tns:abstract-car" />
	<element name="electric-car" type="tns:electric-vehicle" substitutionGroup="tns:abstract-car" />
	<element name="hybrid-car" type="tns:hybrid-vehicle" substitutionGroup="tns:abstract-car" />

</schema>

=== selfdenied/xml-task/data/cars.xml
<?xml version="1.0" encoding="UTF-8"?>
<cars xmlns="http://www.example.org/cars" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/cars cars.xsd ">

	<combustion-car id="c1110">
		<price>10000</price>
		<speed>210</speed>
		<weight>1560</weight>
		<consumption>7.1</consumption>
		<bodystyle>Saloon</bodystyle>
		<drive>FWD</drive>
		<gearbox>Manual</gearbox>
		<engine fuel="Petrol">
			<cylinders>4</cylinders>
			<displacement>1781</displacement>
			<power>150</power>
			<torque>200</torque>
			<turbo>true</turbo>
		</engine>
	</combustion-car>

	<combustion-car id="c1700">
		<price>15000</price>
		<speed>250</speed>
		<weight>1870</weight>
		<consumption>13.7</consumption>
		<bodystyle>Estate</bodystyle>
		<drive>RWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Petrol">
			<cylinders>6</cylinders>
			<displacement>3278</displacement>
			<power>250</power>
			<torque>340</torque>
			<turbo>false</turbo>
		</engine>
	</combustion-car>

	<combustion-car id="c2329">
		<price>25000</price>
		<speed>250</speed>
		<weight>1700</weight>
		<consumption>9.5</consumption>
		<bodystyle>Coupe</bodystyle>
		<drive>AWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Petrol">
			<cylinders>4</cylinders>
			<displacement>1981</displacement>
			<power>211</power>
			<torque>350</torque>
			<turbo>true</turbo>
		</engine>
	</combustion-car>

	<combustion-car id="c2490">
		<price>9000</price>
		<speed>190</speed>
		<weight>1200</weight>
		<consumption>4.5</consumption>
		<bodystyle>Saloon</bodystyle>
		<drive>FWD</drive>
		<gearbox>Manual</gearbox>
		<engine fuel="Diesel">
			<cylinders>4</cylinders>
			<displacement>1590</displacement>
			<power>120</power>
			<torque>250</torque>
			<turbo>true</turbo>
		</engine>
	</combustion-car>

	<electric-car id="c3332">
		<price>70000</price>
		<speed>200</speed>
		<weight>2200</weight>
		<consumption>1.5</consumption>
		<bodystyle>Saloon</bodystyle>
		<drive>AWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Electricity">
			<epower>420</epower>
			<etorque>750</etorque>
		</engine>
	</electric-car>

	<hybrid-car id="c7711">
		<price>34000</price>
		<speed>216</speed>
		<weight>1390</weight>
		<consumption>3.5</consumption>
		<bodystyle>Hatchback</bodystyle>
		<drive>FWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Petrol">
			<cylinders>4</cylinders>
			<displacement>1466</displacement>
			<power>105</power>
			<torque>170</torque>
			<turbo>false</turbo>
		</engine>
		<engine fuel="Electricity">
			<epower>70</epower>
			<etorque>150</etorque>
		</engine>
	</hybrid-car>

	<combustion-car id="c0077">
		<price>5000</price>
		<speed>167</speed>
		<weight>1200</weight>
		<consumption>5.9</consumption>
		<bodystyle>Estate</bodystyle>
		<drive>FWD</drive>
		<gearbox>Manual</gearbox>
		<engine fuel="Diesel">
			<cylinders>4</cylinders>
			<displacement>1598</displacement>
			<power>110</power>
			<torque>205</torque>
			<turbo>true</turbo>
		</engine>
	</combustion-car>

	<combustion-car id="c4545">
		<price>7000</price>
		<speed>175</speed>
		<weight>1400</weight>
		<consumption>9.1</consumption>
		<bodystyle>Offroad</bodystyle>
		<drive>AWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Diesel">
			<cylinders>6</cylinders>
			<displacement>3784</displacement>
			<power>220</power>
			<torque>295</torque>
			<turbo>false</turbo>
		</engine>
	</combustion-car>

	<combustion-car id="c9943">
		<price>75000</price>
		<speed>250</speed>
		<weight>2400</weight>
		<consumption>19.1</consumption>
		<bodystyle>Saloon</bodystyle>
		<drive>AWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Petrol">
			<cylinders>12</cylinders>
			<displacement>6231</displacement>
			<power>550</power>
			<torque>900</torque>
			<turbo>true</turbo>
		</engine>
	</combustion-car>

	<combustion-car id="c8800">
		<price>42300</price>
		<speed>241</speed>
		<weight>2890</weight>
		<consumption>11.5</consumption>
		<bodystyle>Cabriolet</bodystyle>
		<drive>RWD</drive>
		<gearbox>Manual</gearbox>
		<engine fuel="Petrol">
			<cylinders>8</cylinders>
			<displacement>4253</displacement>
			<power>354</power>
			<torque>430</torque>
			<turbo>false</turbo>
		</engine>
	</combustion-car>

	<electric-car id="c1111">
		<price>30000</price>
		<speed>170</speed>
		<weight>1630</weight>
		<consumption>0.9</consumption>
		<bodystyle>Hatchback</bodystyle>
		<drive>FWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Electricity">
			<epower>130</epower>
			<etorque>300</etorque>
		</engine>
	</electric-car>

	<hybrid-car id="c4499">
		<price>38000</price>
		<speed>190</speed>
		<weight>1475</weight>
		<consumption>3.9</consumption>
		<bodystyle>Saloon</bodystyle>
		<drive>FWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Diesel">
			<cylinders>4</cylinders>
			<displacement>1399</displacement>
			<power>122</power>
			<torque>225</torque>
			<turbo>true</turbo>
		</engine>
		<engine fuel="Electricity">
			<epower>40</epower>
			<etorque>130</etorque>
		</engine>
	</hybrid-car>

	<combustion-car id="c8823">
		<price>4000</price>
		<speed>164</speed>
		<weight>1180</weight>
		<consumption>5.5</consumption>
		<bodystyle>Cabriolet</bodystyle>
		<drive>RWD</drive>
		<gearbox>Manual</gearbox>
		<engine fuel="Petrol">
			<cylinders>4</cylinders>
			<displacement>1991</displacement>
			<power>140</power>
			<torque>206</torque>
			<turbo>false</turbo>
		</engine>
	</combustion-car>

	<electric-car id="c2690">
		<price>37000</price>
		<speed>200</speed>
		<weight>1570</weight>
		<consumption>1.3</consumption>
		<bodystyle>Coupe</bodystyle>
		<drive>RWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Electricity">
			<epower>260</epower>
			<etorque>500</etorque>
		</engine>
	</electric-car>

	<electric-car id="c7676">
		<price>90000</price>
		<speed>210</speed>
		<weight>1970</weight>
		<consumption>1.7</consumption>
		<bodystyle>Saloon</bodystyle>
		<drive>RWD</drive>
		<gearbox>Automatic</gearbox>
		<engine fuel="Electricity">
			<epower>390</epower>
			<etorque>735</etorque>
		</engine>
	</electric-car>

</cars>
